services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crm_loan_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backenddjango
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn crm_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backenddjango:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - POSTGRES_DB=crm_loan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

  celery:
    build: ./backenddjango
    command: >
      sh -c "python manage.py wait_for_db &&
             celery -A crm_backend worker -l info"
    volumes:
      - ./backenddjango:/app
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=1
      - POSTGRES_DB=crm_loan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

  celery-beat:
    build: ./backenddjango
    command: >
      sh -c "python manage.py wait_for_db &&
             celery -A crm_backend beat -l info"
    volumes:
      - ./backenddjango:/app
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=1
      - POSTGRES_DB=crm_loan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  static_volume:
  media_volume:
